config: config/base.yaml
coord_init:
  type: sparse
debug: false
exid: 174582347336
experiment: experiment_exp2_32
experiment_dir: log/complex_21_b3a67198
initial: circle
log_dir: log/
loss:
  bis_loss_weight: null
  use_distance_weighted_loss: true
  use_l1_loss: false
  xing_loss_weight: 0.01
lr_base:
  bg: 0.01
  color: 0.01
  point: 1
  stroke_color: null
  stroke_width: null
num_iter: 300
num_segments: 4
path_schedule:
  base: 2
  max_path: 158
  max_path_per_iter: 128
  type: exp
save:
  image: true
  init: true
  loss: false
  output: true
  video: false
seed: null
seginit:
  radius: 5
  type: circle
signature: complex_21_b3a67198
target: dataset/complex_21.png
trainable:
  bg: true
  record: true
  stroke: false
use_ycrcb: false
