config: config/base.yaml
coord_init:
  type: sparse
debug: false
exid: 174582663361
experiment: experiment_exp2_32
experiment_dir: log/truth_1_3d71bfae
initial: circle
log_dir: log/
loss:
  bis_loss_weight: null
  use_distance_weighted_loss: true
  use_l1_loss: false
  xing_loss_weight: 0.01
lr_base:
  bg: 0.01
  color: 0.01
  point: 1
  stroke_color: null
  stroke_width: null
num_iter: 300
num_segments: 4
path_schedule:
  base: 2
  max_path: 244
  max_path_per_iter: 128
  type: exp
save:
  image: true
  init: true
  loss: false
  output: true
  video: false
seed: null
seginit:
  radius: 5
  type: circle
signature: truth_1_3d71bfae
target: dataset/truth_1.jpg
trainable:
  bg: true
  record: true
  stroke: false
use_ycrcb: false
